# Generated by Django 4.2.4 on 2023-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('coll', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='pics')),
            ],
        ),
    ]
